//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_xedap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBWebBanXeDapEntities : DbContext
    {
        public DBWebBanXeDapEntities()
            : base("name=DBWebBanXeDapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCategory> tCategories { get; set; }
        public virtual DbSet<tCountry> tCountries { get; set; }
        public virtual DbSet<tCustumer> tCustumers { get; set; }
        public virtual DbSet<tMembership> tMemberships { get; set; }
        public virtual DbSet<tOrder> tOrders { get; set; }
        public virtual DbSet<tOrder_detall> tOrder_detall { get; set; }
        public virtual DbSet<tProduct> tProducts { get; set; }
        public virtual DbSet<tProduct_Img> tProduct_Img { get; set; }
        public virtual DbSet<tSubstance> tSubstances { get; set; }
        public virtual DbSet<tSupplier> tSuppliers { get; set; }
    }
}
