//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_xedap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrder
    {
        public string OrderID { get; set; }
        public string CustumerID { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
    
        public virtual tCustumer tCustumer { get; set; }
        public virtual tMembership tMembership { get; set; }
        public virtual tOrder_detall tOrder_detall { get; set; }
    }
}
