//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_xedap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProduct()
        {
            this.tOrder_detall = new HashSet<tOrder_detall>();
            this.tProduct_Img = new HashSet<tProduct_Img>();
        }
    
        public string ProductID { get; set; }
        public string ProducName { get; set; }
        public string Color { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<double> Price { get; set; }
        public string MaLoai { get; set; }
        public string MaChatLieu { get; set; }
        public string MaNSX { get; set; }
        public string MaAnh { get; set; }
        public string GioiThieu { get; set; }
        public Nullable<int> Discount { get; set; }
        public string BaoHanh { get; set; }
        public string MaNuoc { get; set; }
        public string Anh { get; set; }
    
        public virtual tCategory tCategory { get; set; }
        public virtual tCountry tCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrder_detall> tOrder_detall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProduct_Img> tProduct_Img { get; set; }
        public virtual tSubstance tSubstance { get; set; }
        public virtual tSupplier tSupplier { get; set; }
    }
}
